language: node_js

node_js:
  - stable

install:
  - npm install

before_install:
    - (cd module && npm install && npm run build)
    - (cd namespace && npm install && npm run build)

script:
  - npm test

